
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

line_length: 200

#type_body_length:
#  - 300 # warning
#  - 400 # error

function_body_length:
  - 60 # warning
  - 100 # error

type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 60
    error: 80

identifier_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 60
    error: 80
