
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

line_length:
  warning: 300
  # Some improbably large number because we don't want compile errors
  # just because of style problems
  error: 300
  ignores_urls: true
  ignores_comments: true


#type_body_length:
#  - 300 # warning
#  - 400 # error

function_body_length:
  - 60 # warning
  - 100 # error

identifier_name:
  excluded: # excluded names
    - id
    - ok
    - i

enum_case_associated_values_count: # Number of associated values in an enum case should be low
  - 6 # warning - default: 5
  - 7 # error - default: 6


force_cast:
  warning
force_try:
  warning

statement_position:
  statement_mode: uncuddled_else
  
disabled_rules:
  - trailing_whitespace
  - redundant_string_enum_value
  - large_tuple
#  - todo
  - type_name
  - trailing_comma
  - trailing_closure
  - file_length
  - cyclomatic_complexity
  - function_body_length
  - type_body_length

opt_in_rules:
  - private_outlet
  - private_action
  - void_return
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - empty_count
  - discouraged_direct_init
  - duplicate_imports
  - empty_enum_arguments
  - enum_case_associated_values_count
  - redundant_optional_initialization
  - prohibited_super_call
  - overridden_super_call
  - no_space_in_method_call
  
