require 'dotenv'
Dotenv.load

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

# Fastfile
default_platform(:ios)

lane :test do
  puts "FIREBASE_CLI_TOKEN: #{ENV['FIREBASE_CLI_TOKEN']}"
end

firebase_app_ids = {
  "Betsson UAT" => "1:844144342615:ios:9d61f3eb24c40f4f8a9512",
  "Betsson PROD" => "1:519365540506:ios:15a46886b359a568defd23"
}

platform :ios do

  lane :certificates do
    register_devices(devices_file: "./fastlane/devices.txt")

    match(
      type: "adhoc",
      force_for_new_devices: true,
      readonly: false
    )
  end

  lane :distribute_to_firebase do |options|
    app_scheme = options[:app_scheme]

    # Validate scheme
    unless firebase_app_ids.key?(app_scheme)
      UI.user_error!("Invalid scheme: #{app_scheme}. Please provide one of: #{firebase_app_ids.keys.join(', ')}")
    end

    firebase_app_id = firebase_app_ids[app_scheme]

    build_ios_app(
      scheme: app_scheme,
      clean: true,
      silent: true,
      suppress_xcode_output: true,
      export_method: "ad-hoc", # Use ad hoc provisioning profile
      export_options: {
        compileBitcode: false,
        uploadBitcode: false,
        uploadSymbols: true,
        manageAppVersionAndBuildNumber: false
      }
    )

    firebase_app_distribution(
      app: firebase_app_id,
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      groups: "ios-internal", # Replace with your desired distribution group(s)
      debug: true
    )
  end

  lane :betsson_uat do
    desc "Distribute Betsson via UAT version to Firebase"
    distribute_to_firebase(app_scheme: "Betsson UAT")
  end

  lane :betsson_prod do
    desc "Distribute Betsson Prod Beta version to Firebase"
    distribute_to_firebase(app_scheme: "Betsson PROD")
  end
  
end
