require 'dotenv'
Dotenv.load

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

# Fastfile
default_platform(:ios)

lane :test do
  puts "FIREBASE_CLI_TOKEN: #{ENV['FIREBASE_CLI_TOKEN']}"
end

firebase_app_ids = {
  "Betsson UAT" => "1:844144342615:ios:9d61f3eb24c40f4f8a9512",
  "Betsson PROD" => "1:519365540506:ios:15a46886b359a568defd23"
}

apple_ids = {
  "Betsson UAT" => "ruben@gomadevelopment.pt",
  "Betsson PROD" => "ruben@gomadevelopment.pt"
}

app_ids = {
  "Betsson UAT" => "com.gomagaming.betsson",
  "Betsson PROD" => "fr.betsson.ios.app"
}

team_ids = {
  "Betsson UAT" => "422GNXXZJR",
  "Betsson PROD" => "QN2DYX5K4M"
}

platform :ios do

  lane :update_version do
    current_version = get_version_number(xcodeproj: "Sportsbook.xcodeproj")
    current_build = get_build_number(xcodeproj: "Sportsbook.xcodeproj")
    
    new_version = prompt(text: "Current version is #{current_version}. Enter new version number:")
    new_build = prompt(text: "Current build number is #{current_build}. Enter new build number:")

    increment_version_number(version_number: new_version)
    increment_build_number(build_number: new_build)
  end

  lane :certificates do |options|
    app_scheme = options[:app_scheme]

    # Set apple_id and team_id based on app_scheme
    apple_id = apple_ids[app_scheme]
    app_id = app_ids[app_scheme]
    team_id = team_ids[app_scheme]

    register_devices(devices_file: "./fastlane/devices.txt")

    match(
      type: "adhoc",
      force_for_new_devices: true,
      readonly: true,
      app_identifier: app_id,  # Ensure you have the right app identifier
      username: apple_id,
      team_id: team_id
    )
  end

  lane :distribute_to_firebase do |options|
    app_scheme = options[:app_scheme]

    # Validate scheme
    unless firebase_app_ids.key?(app_scheme)
      UI.user_error!("Invalid scheme: #{app_scheme}. Please provide one of: #{firebase_app_ids.keys.join(', ')}")
    end

    firebase_app_id = firebase_app_ids[app_scheme]

    # Call certificates lane with app_scheme
    certificates(app_scheme: app_scheme)

    build_ios_app(
      scheme: app_scheme,
      clean: true,
      silent: true,
      suppress_xcode_output: true,
      skip_profile_detection: true, # default if true, o not try to build a profile mapping from the xcodeproj. Match or a manually provided mapping should be used
      export_method: "ad-hoc", # Use ad hoc provisioning profile
      export_options: {
        compileBitcode: false,
        uploadBitcode: false,
        uploadSymbols: true,
        manageAppVersionAndBuildNumber: false
      }
    )

    firebase_app_distribution(
      app: firebase_app_id,
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      groups: "ios-internal", # Replace with your desired distribution group(s)
      debug: true
    )
  end

  lane :version_bump do
    # Get current build number
    current_build = get_build_number(xcodeproj: "Sportsbook.xcodeproj")
    puts "Current build number (CURRENT_PROJECT_VERSION): #{current_build}"
    
    # Prompt for new build number
    new_build = prompt(text: "Enter new build number (CURRENT_PROJECT_VERSION):")
    
    # Update build number
    increment_build_number(
      build_number: new_build,
      xcodeproj: "Sportsbook.xcodeproj"
    )
    
    puts "Build number updated to: #{new_build}"
  end

  lane :marketing_version_bump do
    # Get current version
    current_version = get_version_number(xcodeproj: "Sportsbook.xcodeproj")
    puts "Current version (MARKETING_VERSION): #{current_version}"
    
    # Prompt for new version
    new_version = prompt(text: "Enter new version number (MARKETING_VERSION):")
    
    # Update version
    increment_version_number(
      version_number: new_version,
      xcodeproj: "Sportsbook.xcodeproj"
    )
    
    puts "Version updated to: #{new_version}"
  end

  lane :betsson_uat do
    desc "Distribute Betsson via UAT version to Firebase"
    distribute_to_firebase(app_scheme: "Betsson UAT")
  end

  lane :betsson_prod do
    desc "Distribute Betsson Prod Beta version to Firebase"
    distribute_to_firebase(app_scheme: "Betsson PROD")
  end

  lane :betsson do
    desc "Distribute both Betsson UAT and Betsson PROD versions to Firebase"
    betsson_uat
    betsson_prod
  end

end
